[package]
name = "image_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webp = "0.2.6"
image = "0.24.8"
clap = { version = "4.4.16", features = ["derive"] }
